/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type Int = number;
export type Str = string;
export type ObjectArray = {
  Int: Int;
  Str: Str;
  [k: string]: any;
}[];
